[mypy]
mypy_path = src/, typings/
exclude = build/, dist/
strict = True

# Leverage type inference for function return type
disallow_untyped_calls = False
disallow_incomplete_defs = False
disallow_untyped_defs = False

disable_error_code =
  # https://github.com/python/mypy/issues/6232 (redefinition with correct type)
  attr-defined, assignment,

# https://github.com/ronaldoussoren/pyobjc/issues/198
# https://github.com/ronaldoussoren/pyobjc/issues/417
# https://github.com/ronaldoussoren/pyobjc/issues/419
[mypy-objc.*]
follow_untyped_imports = True
[mypy-Quartz.*]
allow_any_generics = True
