# pyright: reportUnknownParameterType=false, reportMissingParameterType=false, reportMissingTypeArgument=false
from typing import Any

CFArrayCreate: Any
CFArrayCreateMutable: Any
CFDictionaryCreate: Any
CFDictionaryCreateMutable: Any
CFSetCreate: Any
CFSetCreateMutable: Any
kCFTypeArrayCallBacks: Any
kCFTypeDictionaryKeyCallBacks: Any
kCFTypeDictionaryValueCallBacks: Any
kCFTypeSetCallBacks: Any

def CFCopyLocalizedString(key, comment): ...
def CFCopyLocalizedStringFromTable(key, tbl, comment): ...
def CFCopyLocalizedStringFromTableInBundle(key, tbl, bundle, comment): ...
def CFCopyLocalizedStringWithDefaultValue(key, tbl, bundle, value, comment): ...
def CFSTR(strval): ...
def CGDataConsumerCreate(*args, **kwargs) -> Any: ...
def CGDataProviderCreateSequential(*args, **kwargs) -> Any: ...
def CGDataProviderCreateWithData(info, data, size, release) -> object: ...
def CGDisplayRegisterReconfigurationCallback(*args, **kwargs) -> Any: ...
def CGDisplayRemoveReconfigurationCallback(*args, **kwargs) -> Any: ...
def CGEventTapCreate(*args, **kwargs) -> Any: ...
def CGEventTapCreateForPSN(*args, **kwargs) -> Any: ...
def CGFunctionCreate(
    info, domainDimension, domain, rangeDimension, range, evaluate
) -> Any: ...
def CGPSConverterCreate(*args, **kwargs) -> Any: ...
def CGPatternCreate(*args, **kwargs) -> Any: ...
def CGRegisterScreenRefreshCallback(*args, **kwargs) -> Any: ...
def CGScreenRegisterMoveCallback(*args, **kwargs) -> Any: ...
def CGScreenUnregisterMoveCallback(*args, **kwargs) -> Any: ...
def CGUnregisterScreenRefreshCallback(*args, **kwargs) -> Any: ...
def CGBitmapContextCreate(*args, **kwargs) -> Any: ...
def CGBitmapContextCreateWithData(*args, **kwargs) -> Any: ...
def CGFontCopyTableTags(*args, **kwargs) -> Any: ...
def CGPDFObjectGetValue(*args, **kwargs) -> Any: ...
def CGWindowListCreate(*args, **kwargs) -> Any: ...
def CGWindowListCreateDescriptionFromArray(*args, **kwargs) -> Any: ...
def CGWindowListCreateImageFromArray(*args, **kwargs) -> Any: ...
def CGReleaseScreenRefreshRects(*args, **kwargs) -> Any: ...
def CGWaitForScreenRefreshRects(*args, **kwargs) -> Any: ...
def CGWaitForScreenUpdateRects(*args, **kwargs) -> Any: ...

_inline_list_: Any

def sel32or64(a, b): ...
def selAorI(a, b): ...

misc: Any
constants: str
enums: str
functions: Any
aliases: Any
cftypes: Any
expressions: Any

def CGPDFDictionaryApplyFunction(*args, **kwargs) -> Any: ...
def CGPathApply(*args, **kwargs) -> Any: ...
def setCGPathElement(*args, **kwargs) -> Any: ...

class CGSavedGState:
    context: Any
    def __init__(self, context) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, exc_tp): ...

class CGTransparencyLayer:
    context: Any
    info: Any
    rect: Any
    def __init__(self, context, info, rect: Any | None = ...) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, exc_tp): ...

class CGContextPage:
    context: Any
    mediaBox: Any
    def __init__(self, context, mediaBox: Any | None = ...) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, exc_tp): ...
